---
# tasks file for install-tools/haproxy
- name: Install Haproxy for LB
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - haproxy

- name: Configure Haproxy
  template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"

- name: start Haproxy for LB
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items: 
    - haproxy