---
# tasks file for install-tools/kubernetes

# The kubectl command line utility is used to interact with the Kubernetes API Server. Download and install kubectl from the official release binaries:
- name: Download and install kubectl
  get_url:
    url: "{{ item }}"
    dest: "{{ KUBERNETES_BINARY_PATH }}"
    mode: '0700'
  with_items:
    - "https://storage.googleapis.com/kubernetes-release/release/{{ KUBERNETES_VERSION }}/bin/linux/amd64/kubectl" 

- name: Verify kubectl version 1.18.6 or higher is installed
  shell: "{{ KUBERNETES_BINARY_PATH }}/kubectl version --client"      
  register: kubectl_version        

- debug:
    msg: 
      - "kubectl version : {{ kubectl_version.stdout_lines[0] }}" 
    verbosity: 2      

- name: Enable kubectl autocompletion (1/2)
  yum: 
    name: bash-completion
    state: installed

- name: Enable kubectl autocompletion (2/2)
  shell: | 
    {{ KUBERNETES_BINARY_PATH }}/kubectl completion bash > /etc/bash_completion.d/kubectl  