---
- hosts: 'kube-master' 
  gather_facts: False
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:

    - name: Generator Token for kubernetes cluster
      shell: |
        kubeadm token generate
      register: generate_token 

    - set_fact:
        string_to_token: "{{ generate_token.stdout }}"
        
    - name: Create Cluster with kubeadm
      shell: |
        kubeadm init --token {{ string_to_token }} --apiserver-advertise-address {{ hostvars[inventory_hostname].ansible_host }} --kubernetes-version $(kubeadm version -o short) --pod-network-cidr=10.244.0.0/16
    
    - name: Create a Directory for the Kubernetes Cluster
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Enable kubectl/kubeadm autocompletion (1/2)
      yum: 
        name: bash-completion
        state: installed

    - name: Enable kubectl/kubeadm autocompletion (1/2)
      shell: | 
        kubectl completion bash > /etc/bash_completion.d/kubectl 
        kubeadm completion bash > /etc/bash_completion.d/kubeadm 

    - name: Pod Network Add-On (Flannel)
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml