---
# tasks file for boostrapping/etcd
- name: Download and Install the etcd Binaries (1/2)
  unarchive:
    src: "{{ item }}"
    dest: "/tmp" 
    remote_src: yes
  with_items:
    - "https://storage.googleapis.com/etcd/{{ ETCD_VER }}/etcd-{{ ETCD_VER }}-linux-amd64.tar.gz"

- name: Download and Install the etcd Binaries (2/2)
  copy: 
    src: "/tmp/etcd-{{ ETCD_VER }}-linux-amd64/{{ item }}"
    dest: "{{ KUBERNETES_BINARY_PATH }}"
    mode: 0700
    remote_src: yes
  with_items:
    - etcd
    - etcdctl

- name: Recursively remove directory
  file:
    path: "/tmp/etcd-{{ ETCD_VER }}-linux-amd64/"
    state: absent

- name: Configure the etcd Server (1/2)
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  with_items:
    - "/etc/etcd"
    - "/var/lib/etcd" 

- name: Configure the etcd Server (2/2)
  copy: 
    src: "{{ KUBERNETES_DIRECTORY }}/{{ item }}"
    dest: "/etc/etcd"
    mode: 0600
    remote_src: yes
  with_items:
    - pki/ca/ca.pem 
    - pki/api/kubernetes-key.pem
    - pki/api/kubernetes.pem

- name: Create the etcd.service systemd unit file
  template: 
    src: "etcd.service.j2"
    dest: "/etc/systemd/system/etcd.service"
    mode: 0700

- name: Start the etcd Server
  systemd:
    name: "{{ item }}" 
    daemon_reload: yes
    state: restarted
    enabled: yes
  with_items:
    - etcd

- name: Verification ETCD
  shell: >
    ETCDCTL_API=3 {{ KUBERNETES_BINARY_PATH }}/etcdctl member list 
    --endpoints=https://127.0.0.1:2379 
    --cacert=/etc/etcd/ca.pem 
    --cert=/etc/etcd/kubernetes.pem 
    --key=/etc/etcd/kubernetes-key.pem
  register: "verification_result" 

- debug:
    msg: 
      - "Verification result :  {{ verification_result.stdout_lines }} " 
    verbosity: 0     