---
- name: Download Docker Repository
  copy:
    dest: /etc/yum.repos.d/docker-ce.repo 
    content: |
      [docker-ce-stable]
      name=Docker CE Stable - $basearch
      baseurl=https://download.docker.com/linux/centos/7/$basearch/stable
      enabled=1
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg  

- name: Install pakcage for Docker
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
  
- name: Enable Docker Serivce
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - docker  