---
# tasks file for install-tools/cfssl
# The cfssl and cfssljson command line utilities will be used to provision a PKI Infrastructure and generate TLS certificates
- name: Download and install cfssl and cfssljson
  get_url:
    url: "{{ item }}"
    dest: "{{ KUBERNETES_BINARY_PATH }}"
    mode: '0700'
  with_items:
    - "https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssl"
    - "https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssljson"

- name: Verify cfssl version 1.4.1 or higher is installed
  shell: "{{ KUBERNETES_BINARY_PATH }}/cfssl version"
  register: cfssl_version

- name: Verify cfssljson version 1.4.1 or higher is installed
  shell: "{{ KUBERNETES_BINARY_PATH }}/cfssljson --version"      
  register: cfssljson_version

- debug:
    msg: 
      - "cfssl version : {{ cfssl_version.stdout_lines[0] }}"
      - "cfssljson version : {{ cfssljson_version.stdout_lines[0] }}"
    verbosity: 2