---
# The Admin Certificate  
- name: Generate the admin certificate and private key (1/2)
  template:
    src: "admin-csr.json.j2"
    dest: "{{ KUBERNETES_DIRECTORY }}/pki/admin/admin-csr.json"    

## json pretty format : cat ~/pki/xx.json | python -m json.tool
- name: Generate the admin certificate and private key (2/2)
  copy:
    dest: "{{ KUBERNETES_DIRECTORY }}/gencert-admin.sh"
    content: |
      #/usr/bin/env bash
      {{ KUBERNETES_BINARY_PATH }}/cfssl gencert \
      -ca={{ KUBERNETES_DIRECTORY }}/pki/ca/ca.pem \
      -ca-key={{ KUBERNETES_DIRECTORY }}/pki/ca/ca-key.pem \
      -config={{ KUBERNETES_DIRECTORY }}/pki/config/ca-config.json \
      -profile=kubernetes \
      {{ KUBERNETES_DIRECTORY }}/pki/admin/admin-csr.json \
      | {{ KUBERNETES_BINARY_PATH }}/cfssljson -bare {{ KUBERNETES_DIRECTORY }}/pki/admin/admin
    mode: 0700

- name: Certificate Authority
  shell: "{{ KUBERNETES_DIRECTORY }}/gencert-admin.sh"
  register: admin_result 

- debug:
    msg: 
      - "admin result : {{ admin_result }}" 
    verbosity: 2 