---
# 1. The kubelet Kubernetes Configuration File
- name: Generate a kubeconfig file for the kube-controller-manager service (1/2)
#  shell: >
  copy:
    dest: "{{ KUBERNETES_DIRECTORY }}/genconfig-controller.sh"
    content: |
      #/usr/bin/env bash

      {{ KUBERNETES_BINARY_PATH }}/kubectl config set-cluster {{ KUBERNETS_CLUSTER_NAME }} \
      --certificate-authority={{ KUBERNETES_DIRECTORY }}/pki/ca/ca.pem \
      --embed-certs=true \
      --server=https://{{ KUBERNETES_PUBLIC_ADDRESS }}:6443 \
      --kubeconfig={{ KUBERNETES_DIRECTORY }}/kubeconfig/kube-controller-manager.kubeconfig \
        
      {{ KUBERNETES_BINARY_PATH }}/kubectl config set-credentials system:kube-controller-manager \
      --client-certificate={{ KUBERNETES_DIRECTORY }}/pki/controller/kube-controller-manager.pem \
      --client-key={{ KUBERNETES_DIRECTORY }}/pki/controller/kube-controller-manager-key.pem \
      --embed-certs=true \
      --kubeconfig={{ KUBERNETES_DIRECTORY }}/kubeconfig/kube-controller-manager.kubeconfig
        
      {{ KUBERNETES_BINARY_PATH }}/kubectl config set-context default \
      --cluster={{ KUBERNETS_CLUSTER_NAME }} \
      --user=system:kube-controller-manager \
      --kubeconfig={{ KUBERNETES_DIRECTORY }}/kubeconfig/kube-controller-manager.kubeconfig \
        
      {{ KUBERNETES_BINARY_PATH }}/kubectl config use-context default --kubeconfig={{ KUBERNETES_DIRECTORY }}/kubeconfig/kube-controller-manager.kubeconfig 
    mode: 0700 

- name: Generate a kubeconfig file for the kube-controller-manager service (2/2)
  shell: "{{ KUBERNETES_DIRECTORY }}/genconfig-controller.sh"
  register: "controller_result" 

- debug:
    msg: 
      - "controller result :  {{ controller_result }} " 
    verbosity: 2 